name: Php-SandBox Sample Workflow
on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build_job_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 1 Php-Sandbox Custom Build Step
        run: echo 'Php-Sandbox'

      - name: 2 Check Installed composer version
        run: composer --version

      - name: 3 Validate composer.json and composer.lock
        run: composer validate --strict

      - name: 4 Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: 5 Install dependencies
        run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        run: composer run-script test
